### ISSUE TITLE
Doesn't parse output of catalogue correctly

### ISSUE THREAD

**Issue by madAndroid** [lynxman/hiera-consul#12]
Hi, great tool, thanks!

I'm getting this when querying consul for a service in the catalogue, not sure exactly why it's happening:
```
[root@core ~]# hiera -d -c /srv/puppet/hiera.yaml consul
DEBUG: 2015-08-20 11:45:10 +0000: Hiera YAML backend starting
DEBUG: 2015-08-20 11:45:10 +0000: Looking up consul in YAML backend
DEBUG: 2015-08-20 11:45:10 +0000: Looking for data source locations/common
DEBUG: 2015-08-20 11:45:10 +0000: Cannot find datafile /srv/puppet/hieradata/locations/common.yaml, skipping
DEBUG: 2015-08-20 11:45:10 +0000: Looking for data source common
DEBUG: 2015-08-20 11:45:10 +0000: [eyaml_backend]: Hiera eYAML backend starting
DEBUG: 2015-08-20 11:45:10 +0000: [eyaml_backend]: Set option: datadir = /srv/puppet/hieradata
DEBUG: 2015-08-20 11:45:10 +0000: [eyaml_backend]: Set option: pkcs7_private_key = /etc/puppet/keys/private_key.pkcs7.pem
DEBUG: 2015-08-20 11:45:10 +0000: [eyaml_backend]: Set option: pkcs7_public_key = /etc/puppet/keys/public_key.pkcs7.pem
DEBUG: 2015-08-20 11:45:10 +0000: [eyaml_backend]: Looking up consul in eYAML backend
DEBUG: 2015-08-20 11:45:10 +0000: [eyaml_backend]: Looking for data source locations/common
DEBUG: 2015-08-20 11:45:10 +0000: Cannot find datafile /srv/puppet/hieradata/locations/common.eyaml, skipping
DEBUG: 2015-08-20 11:45:10 +0000: [eyaml_backend]: Looking for data source common
DEBUG: 2015-08-20 11:45:10 +0000: Cannot find datafile /srv/puppet/hieradata/common.eyaml, skipping
DEBUG: 2015-08-20 11:45:10 +0000: [hiera-consul] Client configured to connect to 127.0.0.1:8500
DEBUG: 2015-08-20 11:45:10 +0000: [hiera-consul] Looking up /v1/catalog/service/consul in consul backend
/usr/share/ruby/base64.rb:58:in `decode64': undefined method `unpack' for nil:NilClass (NoMethodError)
        from /usr/local/share/gems/gems/hiera-consul-0.0.3/lib/hiera/backend/consul_backend.rb:113:in `parse_result'
        from /usr/local/share/gems/gems/hiera-consul-0.0.3/lib/hiera/backend/consul_backend.rb:68:in `block in lookup'
        from /usr/local/share/gems/gems/hiera-consul-0.0.3/lib/hiera/backend/consul_backend.rb:51:in `each'
        from /usr/local/share/gems/gems/hiera-consul-0.0.3/lib/hiera/backend/consul_backend.rb:51:in `lookup'
        from /usr/share/ruby/vendor_ruby/hiera/backend.rb:206:in `block in lookup'
        from /usr/share/ruby/vendor_ruby/hiera/backend.rb:203:in `each'
        from /usr/share/ruby/vendor_ruby/hiera/backend.rb:203:in `lookup'
        from /usr/share/ruby/vendor_ruby/hiera.rb:60:in `lookup'
        from /bin/hiera:225:in `<main>'
```
adding some debugging shows that the value being retrieved from consul contains:
```
[{"Node"=>"core", "Address"=>"10.100.10.100", "ServiceID"=>"consul", "ServiceName"=>"consul", "ServiceTags"=>[], "ServiceAddress"=>"", "ServicePort"=>8300}]
```
which is consistent with a curl to the locally running consul instance:
```
[root@core ~]# curl http://0:8500/v1/catalog/service/consul
[{"Node":"core","Address":"10.100.10.100","ServiceID":"consul","ServiceName":"consul","ServiceTags":[],"ServiceAddress":"","ServicePort":8300}]
```

Is the code expecting the result of the query to be in a different format perhaps?

**Comment by madAndroid** [comment]
Ah, looks like the catalogue doesn't have the same structure as the k/v store, afaict ... is that something that changes in consul perhaps?

**Comment by madAndroid** [comment]
Apologies for the confusion, was using quite an old version installed from Rubygems - when pointed directly at the github repo, it appears to work as intended
