### ISSUE TITLE
 backend throws `initialize': undefined method `[]' for nil:NilClass  when used

### ISSUE THREAD

**Issue by stefanandres** [lynxman/hiera-consul#4]
I'd really like to try this backend, but I always get the following error:
```
$ RUBYLIB=/opt/puppet-upstream/hiera_consul/lib hiera foo
WARN: 2015-03-12 14:26:42 +0100: Not using Hiera::Puppet_logger. It does not report itself to be suitable.
/opt/puppet-upstream/hiera_consul/lib/hiera/backend/consul_backend.rb:11:in `initialize': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/vendor_ruby/hiera/backend.rb:205:in `new'
	from /usr/lib/ruby/vendor_ruby/hiera/backend.rb:205:in `block in lookup'
	from /usr/lib/ruby/vendor_ruby/hiera/backend.rb:203:in `each'
	from /usr/lib/ruby/vendor_ruby/hiera/backend.rb:203:in `lookup'
	from /usr/lib/ruby/vendor_ruby/hiera.rb:60:in `lookup'
	from /usr/bin/hiera:225:in `<main>'
```

**Comment by stefanandres** [comment]
Ah pointed out on #puppet that may be because the backend is not configured in the hiera.yaml yet, I'd expect another error (or none when not configured) for that. I'll check that.

**Comment by stefanandres** [comment]
Yep, when configured, the error disappear, but may there be a better way to throw those errors to be meaningful?

**Comment by lynxman** [comment]
Hi Stefan,

You're absolutely right, I'll add a small fix for this.

Thanks!

**Comment by lynxman** [comment]
Just released this, thanks again!
