### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by kyleodonnell** [lynxman/hiera-consul#5]
hello
im trying to use an ssl enabled consul, which works with curl:
```
curl -k --cert consul.cert --key consul.key --cacert ca.cert https://localhost:9443/v1/kv/db/tim/iswhat
[{"CreateIndex":179,"ModifyIndex":179,"LockIndex":0,"Key":"db/tim/iswhat","Flags":0,"Value":"myvalue"}]
```
but when i query using hiera something is wrong, do you know what format the certificates/keys need to be in?  i am using the same format the agent uses:
```
# hiera -d tim/iswhat
DEBUG: Mon Mar 30 17:38:56 +0000 2015: Hiera YAML backend starting
DEBUG: Mon Mar 30 17:38:56 +0000 2015: Looking up tim/iswhat in YAML backend
DEBUG: Mon Mar 30 17:38:56 +0000 2015: Looking for data source defaults
DEBUG: Mon Mar 30 17:38:56 +0000 2015: Cannot find datafile /var/lib/hiera/defaults.yaml, skipping
DEBUG: Mon Mar 30 17:38:56 +0000 2015: Looking for data source global
DEBUG: Mon Mar 30 17:38:56 +0000 2015: Cannot find datafile /var/lib/hiera/global.yaml, skipping
/etc/puppet/modules/hiera_consul/lib/hiera/backend/consul_backend.rb:30:in `initialize': Neither PUB key nor PRIV key:: nested asn1 error (OpenSSL::PKey::RSAError)
	from /etc/puppet/modules/hiera_consul/lib/hiera/backend/consul_backend.rb:30:in `new'
	from /etc/puppet/modules/hiera_consul/lib/hiera/backend/consul_backend.rb:30:in `initialize'
	from /var/lib/gems/1.8/gems/hiera-1.3.4/lib/hiera/backend.rb:205:in `new'
	from /var/lib/gems/1.8/gems/hiera-1.3.4/lib/hiera/backend.rb:205:in `lookup'
	from /var/lib/gems/1.8/gems/hiera-1.3.4/lib/hiera/backend.rb:203:in `each'
	from /var/lib/gems/1.8/gems/hiera-1.3.4/lib/hiera/backend.rb:203:in `lookup'
	from /var/lib/gems/1.8/gems/hiera-1.3.4/lib/hiera.rb:60:in `lookup'
	from /var/lib/gems/1.8/gems/hiera-1.3.4/bin/hiera:225
	from /usr/local/bin/hiera:19:in `load'
	from /usr/local/bin/hiera:19
```

here is my hiera.yaml
```
# cat /etc/hiera.yaml 
---
:backends:
  - yaml
  - consul

:hierarchy:
  - defaults
  - "%{clientcert}"
  - "%{environment}"
  - global

:yaml:
# datadir is empty here, so hiera uses its defaults:
# - /var/lib/hiera on *nix
# - %CommonAppData%\PuppetLabs\hiera\var on Windows
# When specifying a datadir, make sure the directory exists.
  :datadir: /var/lib/hiera

:consul:
  :host: 127.0.0.1 
  :port: 9443
  :use_ssl: true
  :ssl_verify: false
  :ssl_cert: /x/i/consul/etc/ssl/hiera/consul.cert
  :ssl_key: /x/i/consul/etc/ssl/hiera/consul.key
  :ssl_ca_cert: /x/i/consul/etc/ssl/hiera/ca.cert
  :paths:
    - /v1/kv/db
    - /v1/kv/web
    - /v1/kv/app
```

**Comment by kyleodonnell** [comment]
Found and fixed a bug in the consul_backend.rb  PR submitted

https://github.com/lynxman/hiera-consul/pull/7

**Comment by lynxman** [comment]
Hi Kyle,

Thank you so much for your contribution! Sorry I couldn't get to this before
